"""Configuration for the purpose-driven scoring pipeline."""

from __future__ import annotations

DEFAULT_SCORE_WEIGHTS = {
    "purpose_articulation": 0.4,
    "operational_embedding": 0.3,
    "execution_consistency": 0.3,
}

PURPOSE_KEYWORDS = {
    "purpose_core": [
        "mission",
        "why we exist",
        "reason for existence",
        "our purpose",
        "our mission",
        "exist to",
        "founded to",
        "purpose-driven",
        "guided by our credo",
        "credo",
    ],
    "stakeholders": [
        "customers",
        "employees",
        "communities",
        "community",
        "patients",
        "patient",
        "caregivers",
        "health workers",
        "nurses",
        "shareholders",
        "partners",
        "suppliers",
        "society",
        "people",
        "planet",
        "humanity",
        "underserved",
        "all those we serve",
        "small businesses",
    ],
    "impact": [
        "impact",
        "improve",
        "support",
        "enable",
        "empower",
        "protect",
        "transform",
        "opportunity",
        "access",
        "sustainable",
        "sustainability",
        "resilience",
        "affordable",
        "equity",
        "inclusion",
        "well-being",
        "health",
        "healthcare",
        "health equity",
        "for humanity",
    ],
    "branding": [
        "best",
        "delight",
        "world-class",
        "iconic",
        "brand",
        "tagline",
        "premium",
        "love",
    ],
    "leadership": [
        "ceo",
        "chief executive officer",
        "founder",
        "leadership",
        "our leaders",
        "board",
        "chairman",
        "president",
        "vice president",
    ],
    "strategy": [
        "strategy",
        "strategic",
        "priority",
        "long-term",
        "roadmap",
        "growth",
        "initiative",
        "program",
        "business model",
        "corporate direction",
    ],
    "capital": [
        "invest",
        "investment",
        "capital",
        "r&d",
        "research and development",
        "fund",
        "funding",
        "billions",
        "million",
        "allocate",
    ],
    "employees": [
        "employee",
        "employees",
        "workforce",
        "career",
        "training",
        "upskilling",
        "culture",
        "benefits",
        "healthcare",
        "safety",
        "incentive",
    ],
    "execution": [
        "launched",
        "launch",
        "deployed",
        "built",
        "delivered",
        "expanded",
        "rolled out",
        "results",
        "reported",
        "progress",
        "achieved",
        "created",
    ],
    "measurement": [
        "kpi",
        "metric",
        "metrics",
        "measurable",
        "progress",
        "target",
        "goal",
        "outcome",
        "outcomes",
        "percentage",
        "%",
        "million",
        "billion",
        "year-over-year",
    ],
    "capability": [
        "platform",
        "ecosystem",
        "infrastructure",
        "technology",
        "capability",
        "innovation",
        "product",
        "service",
        "solution",
        "network",
    ],
    "industries": [
        "healthcare",
        "education",
        "manufacturing",
        "retail",
        "automotive",
        "finance",
        "energy",
        "government",
        "logistics",
        "small business",
        "consumer",
    ],
}

CORPORATE_PURPOSE_POSITIVE_PATTERNS = [
    "our purpose",
    "our mission",
    "purpose-driven",
    "why we exist",
    "reason for existence",
    "guided by our credo",
    "our credo",
    "we exist to",
    "we are a purpose-driven company",
]

FALSE_PURPOSE_PATTERNS = [
    "purpose-built",
    "built for",
    "mission control",
    "benchmark",
    "architecture",
    "inference",
    "gpu",
    "ai factory",
    "platform",
]

BOILERPLATE_PATTERNS = [
    "trending news and stories",
    "related tags",
    "share",
    "page overview",
    "skip to main",
    "skip to footer",
    "hello, how can i help",
    "menu |",
    "contact us",
    "policies contact",
]

SENTENCE_SPLIT_PATTERN = r"(?<=[.!?])\s+"

DEFAULT_MIN_TEXT_LENGTH = 120
DEFAULT_CHUNK_WORD_SIZE = 180
DEFAULT_TOP_EVIDENCE_COUNT = 5

GENERIC_EVIDENCE_TITLE_PATTERNS = [
    "sustainability",
    "esg",
    "gri",
    "reporting hub",
    "glossary",
    "newsroom",
    "media center",
    "resources",
    "careers",
    "environment",
    "policies and reports",
]

DISPLAY_EXCLUDE_TITLE_PATTERNS = [
    "gri",
    "glossary",
    "reference architecture",
    "benchmark",
    "basepod",
    "mission control",
    "data center solutions",
    "ai factories",
    "corporate social responsibility report",
    "global menu",
    "(untitled)",
]

DISPLAY_EXCLUDE_URL_PATTERNS = [
    "/gri-standards",
    "/glossary/",
    "/technologies/",
    "/data-center/",
    "/solutions/ai-factories",
    "/corporate-social-responsibility/",
    "/u38-global-menu",
]
